### ISSUE TITLE
MVP Task List

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/website-rachel-lewis#36]
### General
- [ ] overall colourscheme, aim for muted / 'paper' effect. Not bright yellow...

### Footer
- [ ] links to social media pages from [icons](http://neginmirsalehi.com/)

### Header
- [ ] take a look at white underline colour choice...
- [x] scrolling is important here
- [ ] take shadow / inspiration from [here](https://github.com/holistic-web/maja/blob/development/src/components/Header.vue)

### Landing Page
- [ ] link to published and performed subsection
- [ ] other posts
- [ ] more content

### About
- [ ] Change the shitty yellow colour
- [ ] Layout overall
- [ ] Get an actual about from rachel

### Collection
- [ ] Published and performed subsection

### Contact:
- [ ] book performances
- [ ] contact me email ting form
