### ISSUE TITLE
Rachel's Checklist:

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/website-rachel-lewis#67]
### Content changes
- [x] replace about content (see [ref1](https://github.com/holistic-web/website-rachel-lewis/issues/67#issuecomment-415693592))
- [x] change title of 'Collection' to 'Published and Performed'
- [x] 'Published and Performed' ['Can you change this from a list to a set of tiles with pictures and words underneath that then link to the page with the work? e.g. https://antoniacundy.com/category/published-work/
- [x] add two titles, ‘Published’ and then ‘Performed’ below it (scroll down the page to see) 
- [x] remove individual 'Published' and 'Performed' pages and replace with filters on the 'Published and Performed' pages
- [ ] add awards to the about page (icons and links) (see [ref2](https://github.com/holistic-web/website-rachel-lewis/issues/67#issuecomment-415693717))
- [ ] get slide pictures from Rachel and replace slides (see [ref3](https://github.com/holistic-web/website-rachel-lewis/issues/67#issuecomment-415693944))

### Page changes
- [ ] add page called 'Latest Obsessions' (to be a blog post page)
- [ ] add page called 'Poetry Projects and Events'
- [ ] add page called 'Get in touch' with contact form and connect to social media accounts. (twitter: @Rachel_Claire_L, insta: @rachel_claire_l) - similar to https://antoniacundy.com/contact/

### Backend changes
- [ ] change url to something similar to 'RachelClaireL'

**Comment by michaelfitzhavey** [comment]
# ref1

### About Text

I am a 23-year-old award-winning poet and performer living and working in London. I make poetry happen through writing, performing, collaborating with other artists and coordinating poetry publications and events. 

Most recently I worked on a collaborative performance with dancers and circus performers at the Roundhouse in Camden (2018) as a Young Producer with Poet in the City (2017). I previously studied English Literature at the University of Cambridge, where I led Chameleon, the university’s creative writing society and was a Poetry Editor for the Mays anthology. 

My poetry has been published by The Poetry Book Society, the Poetry Society, Kindling journal and many more. I have performed on canal towpaths, in cellars underneath feminist pubs, in many a student bar and on the Roundhouse main stage. 

The ‘Performed and published’ section of this website is where you can read and listen to my published work. I’ll let it speak for itself and let you work out what it’s all about yourself. 

Do get in touch if you would like to work with me on any of the following: 

	•	performing at your event
	•	hosting your event 
	•	running a creative writing workshop
	•	commissioning a poem 
	•	collaborating on a creative project 
	•	chatting about poetry in general or in particular

**Comment by michaelfitzhavey** [comment]
# ref2

### Awards for About Page

Can you add these Awards to the about page if you scroll down from my description? just a list in text with links if you click on the text (no ugly links showing!) 

Jun 2016 	Winner, ‘Ways to be Wilder’ YPN Competition, judged by Jen Hadfield	
	http://poems.poetrysociety.org.uk/poems/twenty-tourists-in-a-motor-boat-watching-marine-plankton-bioluminesce/ 

Oct 2015	Highly Commended, Poetry Book Society Student Poetry Competition, judged by Andrew McMillan 

[I will send the PDF of this - can you make it downloadable?] 

Jun 2014	Winner, Cape Farewell’s Poetry Competition with YPN, judged by Helen Mort 

poems.poetrysociety.org.uk/poems/tigerless-2/ 

May 2014	Highly Commended, Words and Women ‘About’ Poetry Competition 

http://wordsandwomennorwich.blogspot.com/search/label/Young%20Women%20Writers 

Jan 2013	Highly commended, T. S. Eliot Prize Writing Competition, essay on new poets

May 2013	Highly Commended, SCJ Poetry Prize, judged by Moniza Alvi and Catherine Smith 

May 2012	Highly commended, Thomas Campion Essay Prize, essay on Keats

Nov 2012	Third Place, Arts Richmond Young Writers Award

Oct 2012	Highly commended in Foyle Young Poets of the Year Award (top 100 out of 14,000 entries) 

May 2012	Winner, Girton College Humanities Writing Competition, won with 2 sonnets

Mar 2011	Winner, Rudyard Kipling Society Essay Writing Competition

Oct 2009 	Highly commended in Foyle Young Poets of the Year Award (top 100 out of 12,000 entries) 

Jun 2009 	Winner, Daunt Books Short Story Competition

2008		Winner, Dramatic Monologue Poetry Competition, judged by Glyn Maxwell

**Comment by michaelfitzhavey** [comment]
# ref3

### Homepage Slides
pictures to use for scrolling pictures: 

For “Published and performed” 



For “Tigerless” 



For “About” 



For “Latest obessions” 



For “Get in touch”

**Comment by michaelfitzhavey** [comment]
closed as issues have been migrated to: https://github.com/holistic-web/website-rachel-lewis/issues/71
